import Foundation
import Combine
import SwiftUI

struct HealthAlert: Identifiable {
    enum Severity {
        case good, warn, bad
        var color: Color {
            switch self {
            case .good: return .green
            case .warn: return .orange
            case .bad:  return .red
            }
        }
    }
    let id = UUID()
    let severity: Severity
    let title: String
    let detail: String
}

struct TodayMetrics {
    let sleepHours: Double?
    let sleepAvg: Double?
    let restingHR: Int?
    let restingHRAvg: Double?
    let steps: Int?
    let stepsAvg: Double?
    let hrv: Double?
    let hrvAvg: Double?

    static let empty = TodayMetrics(
        sleepHours: nil, sleepAvg: nil,
        restingHR: nil, restingHRAvg: nil,
        steps: nil, stepsAvg: nil,
        hrv: nil, hrvAvg: nil
    )
}

/// Loads raw health data for the Home tab: metrics + trend charts.
/// Alerts are now generated by AI (see InsightGenerator), not here.
@MainActor
final class HomeDataLoader: ObservableObject {

    @Published var metrics: TodayMetrics = .empty
    @Published var sleepTrend: [ChartPoint] = []
    @Published var hrvTrend: [ChartPoint] = []
    @Published var isLoading = false
    @Published var loadError: String?

    private(set) var windowDays: Int = 7

    func load(healthStore: HealthStore, days: Int = 7) async {
        windowDays = days
        isLoading = true
        loadError = nil
        defer { isLoading = false }

        do {
            try await healthStore.requestAuthorization()
        } catch {
            loadError = error.localizedDescription
            return
        }

        let cal = Calendar.current
        let today = cal.startOfDay(for: Date())

        var snapshots: [(Date, HealthDaySnapshot)] = []
        for i in (0..<days).reversed() {
            guard let day = cal.date(byAdding: .day, value: -i, to: today) else { continue }
            guard let snap = try? await healthStore.snapshot(for: day) else { continue }
            snapshots.append((day, snap))
        }
        guard let (_, last) = snapshots.last else {
            metrics = .empty; sleepTrend = []; hrvTrend = []; return
        }

        let sleepArr = snapshots.compactMap { $0.1.sleep.asleepMinutes }.map { Double($0) / 60 }
        let restingArr = snapshots.compactMap { $0.1.heart.restingBpm }.map(Double.init)
        let hrvArr = snapshots.compactMap { $0.1.heart.hrvSdnnMs }
        let stepsArr = snapshots.compactMap { $0.1.activity.steps }.map(Double.init)

        metrics = TodayMetrics(
            sleepHours: last.sleep.asleepMinutes.map { Double($0) / 60 },
            sleepAvg: sleepArr.avg,
            restingHR: last.heart.restingBpm,
            restingHRAvg: restingArr.avg,
            steps: last.activity.steps,
            stepsAvg: stepsArr.avg,
            hrv: last.heart.hrvSdnnMs,
            hrvAvg: hrvArr.avg
        )

        sleepTrend = snapshots.compactMap { (day, snap) in
            guard let m = snap.sleep.asleepMinutes else { return nil }
            return ChartPoint(date: day, value: Double(m) / 60)
        }
        hrvTrend = snapshots.compactMap { (day, snap) in
            guard let m = snap.heart.hrvSdnnMs else { return nil }
            return ChartPoint(date: day, value: m)
        }
    }
}

private extension Array where Element == Double {
    var avg: Double? { isEmpty ? nil : reduce(0, +) / Double(count) }
}
